const ActionTypes = {
  SET_EDITOR_CHOICE_DATA: "SET_EDITOR_CHOICE_DATA",
  SET_LATEST_ARTICLE_DATA: "SET_LATEST_ARTICLE_DATA",
  SET_LATEST_REVIEW_DATA: "SET_LATEST_REVIEW_DATA",
  SET_LATEST_REVIEW_PAGE: "SET_LATEST_REVIEW_PAGE",
};

export default ActionTypes;
